export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//Devices
export const SET_DEVICES = 'GET_DEVICES';
export const SET_CURRENT_DEVICE = 'SET_CURRENT_DEVICE';
export const REMOVE_DEVICE = 'REMOVE_DEVICE';


//Customers
export const SET_CUSTOMERS = 'GET_CUSTOMERS';
export const SET_CURRENT_CUSTOMER = 'SET_CURRENT_CUSTOMER';
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';

//Vehicles
export const SET_VEHICLES = 'GET_VEHICLES';
export const SET_CURRENT_VEHICLE = 'SET_CURRENT_VEHICLE';
export const REMOVE_VEHICLE = 'REMOVE_VEHICLE';

//Vehicles socket
export const SET_LIVE_VEHICLES = 'GET_LIVE_VEHICLES';
export const SET_LIVE_VEHICLE = 'SET_LIVE_VEHICLE';
export const SET_VEHICLE_STATUS = 'SET_VEHICLE_STATUS';


//Dealers
export const SET_DEALERS = 'GET_DEALERS';
export const REMOVE_DEALER = 'REMOVE_DEALER';
export const SET_CURRENT_DEALER = 'SET_CURRENT_DEALER';

//Customers
export const SET_DISTRIBUTORS = 'GET_DISTRIBUTORS';
export const SET_CURRENT_DISTRIBUTOR = 'SET_CURRENT_DISTRIBUTOR';
export const REMOVE_DISTRIBUTOR = 'REMOVE_DISTRIBUTOR';

